[workspace]
members = ["cargo:api"]
targets = ["x86_64-unknown-linux-gnu"]
installers = ["shell"]

[release]
updater = true

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# Path that installers should place binaries in
install-path = "${XDG_BIN_HOME:-$HOME/.local/bin}"
# Whether to install an updater program
install-updater = false
profile = "release"