[package]
name = "metta-kg"
version = "0.1.0"
edition = "2021"
build = "build.rs"
description = "MeTTa Knowledge Graph implementation"
repository = "https://github.com/natnael-eyuel-dev/MeTTa-KG"

[package.metadata.dist]
preferred-package = true

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
rocket = { version = "0.5.1", features = ["json"] }
diesel = { version = "2.2.2", features = ["postgres", "chrono"] }
diesel_migrations = "2.3.0"
dotenv = "0.15.0"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.8"
uuid = { version = "1.10.0", features = ["v4"] }
rocket_cors = "0.6.0"
chrono = { version = "0.4.38", features = ["serde"] }
regex = "1.10.6"
reqwest = { version = "0.12.15", features = ["json"] }
urlencoding = "2.1.3"
openssl = { version = "0.10.72", features = ["vendored"] }
pq-sys = { version = "0.6", features = ["bundled"] }
url = "2.5.4"
clap = { version = "4.5.47", features = ["derive"] }
once_cell = "1.20.0"
rust-embed = "8.0.0"
tokio = { version = "1.38.0", features = ["rt", "macros", "time", "process"] }
tempfile = "3.10.1"

[dev-dependencies]
httpmock = "0.7.0"
serial_test = "3.0"

[features]
integration-tests = []
